config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  resources :todos
  root "todos#index"

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/todo.rb
class Todo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
    before_action :set_todo, only: %i[ show edit update destroy ]

    def index
        @todos = Todo.all
    end

    def new 
        @todo = Todo.new
    end

    def show
    end

    def edit 
    end

    def create 
        @todo = Todo.new(todo_params)
        if @todo.save
            redirect_to todos_path, notice: 'Todo was successfully created.'
        else 
            render :new
        end
    end

    def update
        if @todo.update(todo_params)
            head :no_content
        else
            render json: @todo.errors, status: :unprocessable_entity
        end 
    end

    def destroy
        @todo.destroy
        redirect_to todos_path, notice: 'Todo was successfully destroyed.'
    end
    
    private
        def set_todo
            @todo = Todo.find(params[:id])
        end

        def todo_params
            params.require(:todo).permit(:title, :completed)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload", media: 'all' %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/todos/edit.html.erb
<h1>Edit Todo</h1>

<%= form_with model: @todo, local: true do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.label :completed %>
        <%= form.check_box :completed %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<h1>Todo List</h1>

<%= link_to 'New Todo', new_todo_path %>

<ul>
    <% @todos.each do |todo| %>
        <li>
            <%= check_box_tag "todo_#{todo.id}", todo.id, todo.completed, class: 'todo-checkbox', data: { id: todo.id } %>
            <%= todo.title %>
            <%= link_to 'Delete', todo, method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
    <% end %>
</ul>

app/views/todos/new.html.erb
<h1>New Todo</h1>

<%= form_with model: @todo, local: true do |form| %>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div>

    <div>
        <%= form.submit %>
    </div>
<% end %>

<%= link_to 'Back', todos_path %>

app/views/todos/show.html.erb
<h1><%= @todo.title %></h1>

<p>
    <strong>Completed:</strong>
    <%= @todo.completed ? "Yes" : "No" %>
</p>

<%= link_to 'Edit', edit_todo_path(@todo) %> |
<%= link_to 'Back', todos_path %>